const genCards = document.querySelectorAll(".card");
const gen1Card = document.querySelector(".gen1");
const gen2Card = document.querySelector(".gen2");
const gen3Card = document.querySelector(".gen3");
const gen4Card = document.querySelector(".gen4");

let chooseGen;
let userChoice;

const gen1 = [
    { pokedexNumber: 1, pokemon: "bulbasaur" },
    { pokedexNumber: 2, pokemon: "ivysaur" },
    { pokedexNumber: 3, pokemon: "venusaur" },
    { pokedexNumber: 4, pokemon: "charmander" },
    { pokedexNumber: 5, pokemon: "charmeleon" },
    { pokedexNumber: 6, pokemon: "charizard" },
    { pokedexNumber: 7, pokemon: "squirtle" },
    { pokedexNumber: 8, pokemon: "wartortle" },
    { pokedexNumber: 9, pokemon: "blastoise" },
    { pokedexNumber: 10, pokemon: "caterpie" },
    { pokedexNumber: 11, pokemon: "metapod" },
    { pokedexNumber: 12, pokemon: "butterfree" },
    { pokedexNumber: 13, pokemon: "weedle" },
    { pokedexNumber: 14, pokemon: "kakuna" },
    { pokedexNumber: 15, pokemon: "beedrill" },
    { pokedexNumber: 16, pokemon: "pidgey" },
    { pokedexNumber: 17, pokemon: "pidgeotto" },
    { pokedexNumber: 18, pokemon: "pidgeot" },
    { pokedexNumber: 19, pokemon: "rattata" },
    { pokedexNumber: 20, pokemon: "raticate" },
    { pokedexNumber: 21, pokemon: "spearow" },
    { pokedexNumber: 22, pokemon: "fearow" },
    { pokedexNumber: 23, pokemon: "ekans" },
    { pokedexNumber: 24, pokemon: "arbok" },
    { pokedexNumber: 25, pokemon: "pikachu" },
    { pokedexNumber: 26, pokemon: "raichu" },
    { pokedexNumber: 27, pokemon: "sandshrew" },
    { pokedexNumber: 28, pokemon: "sandslash" },
    { pokedexNumber: 29, pokemon: "nidoran f" },
    { pokedexNumber: 30, pokemon: "nidorina" },
    { pokedexNumber: 31, pokemon: "nidoqueen" },
    { pokedexNumber: 32, pokemon: "nidoran m" },
    { pokedexNumber: 33, pokemon: "nidorino" },
    { pokedexNumber: 34, pokemon: "nidoking" },
    { pokedexNumber: 35, pokemon: "clefairy" },
    { pokedexNumber: 36, pokemon: "clefable" },
    { pokedexNumber: 37, pokemon: "vulpix" },
    { pokedexNumber: 38, pokemon: "ninetales" },
    { pokedexNumber: 39, pokemon: "jigglypuff" },
    { pokedexNumber: 40, pokemon: "wigglytuff" },
    { pokedexNumber: 41, pokemon: "zubat" },
    { pokedexNumber: 42, pokemon: "golbat" },
    { pokedexNumber: 43, pokemon: "oddish" },
    { pokedexNumber: 44, pokemon: "gloom" },
    { pokedexNumber: 45, pokemon: "vileplume" },
    { pokedexNumber: 46, pokemon: "paras" },
    { pokedexNumber: 47, pokemon: "parasect" },
    { pokedexNumber: 48, pokemon: "venonat" },
    { pokedexNumber: 49, pokemon: "venomoth" },
    { pokedexNumber: 50, pokemon: "diglett" },
    { pokedexNumber: 51, pokemon: "dugtrio" },
    { pokedexNumber: 52, pokemon: "meowth" },
    { pokedexNumber: 53, pokemon: "persian" },
    { pokedexNumber: 54, pokemon: "psyduck" },
    { pokedexNumber: 55, pokemon: "golduck" },
    { pokedexNumber: 56, pokemon: "mankey" },
    { pokedexNumber: 57, pokemon: "primeape" },
    { pokedexNumber: 58, pokemon: "growlithe" },
    { pokedexNumber: 59, pokemon: "arcanine" },
    { pokedexNumber: 60, pokemon: "poliwag" },
    { pokedexNumber: 61, pokemon: "poliwhirl" },
    { pokedexNumber: 62, pokemon: "poliwrath" },
    { pokedexNumber: 63, pokemon: "abra" },
    { pokedexNumber: 64, pokemon: "kadabra" },
    { pokedexNumber: 65, pokemon: "alakazam" },
    { pokedexNumber: 66, pokemon: "machop" },
    { pokedexNumber: 67, pokemon: "machoke" },
    { pokedexNumber: 68, pokemon: "machamp" },
    { pokedexNumber: 69, pokemon: "bellsprout" },
    { pokedexNumber: 70, pokemon: "weepinbell" },
    { pokedexNumber: 71, pokemon: "victreebel" },
    { pokedexNumber: 72, pokemon: "tentacool" },
    { pokedexNumber: 73, pokemon: "tentacruel" },
    { pokedexNumber: 74, pokemon: "geodude" },
    { pokedexNumber: 75, pokemon: "graveler" },
    { pokedexNumber: 76, pokemon: "golem" },
    { pokedexNumber: 77, pokemon: "ponyta" },
    { pokedexNumber: 78, pokemon: "rapidash" },
    { pokedexNumber: 79, pokemon: "slowpoke" },
    { pokedexNumber: 80, pokemon: "slowbro" },
    { pokedexNumber: 81, pokemon: "magnemite" },
    { pokedexNumber: 82, pokemon: "magneton" },
    { pokedexNumber: 83, pokemon: "farfetch'd" },
    { pokedexNumber: 84, pokemon: "doduo" },
    { pokedexNumber: 85, pokemon: "dodrio" },
    { pokedexNumber: 86, pokemon: "seel" },
    { pokedexNumber: 87, pokemon: "dewgong" },
    { pokedexNumber: 88, pokemon: "grimer" },
    { pokedexNumber: 89, pokemon: "muk" },
    { pokedexNumber: 90, pokemon: "shellder" },
    { pokedexNumber: 91, pokemon: "cloyster" },
    { pokedexNumber: 92, pokemon: "gastly" },
    { pokedexNumber: 93, pokemon: "haunter" },
    { pokedexNumber: 94, pokemon: "gengar" },
    { pokedexNumber: 95, pokemon: "onix" },
    { pokedexNumber: 96, pokemon: "drowzee" },
    { pokedexNumber: 97, pokemon: "hypno" },
    { pokedexNumber: 98, pokemon: "krabby" },
    { pokedexNumber: 99, pokemon: "kingler" },
    { pokedexNumber: 100, pokemon: "voltorb" },
    { pokedexNumber: 101, pokemon: "electrode" },
    { pokedexNumber: 102, pokemon: "exeggcute" },
    { pokedexNumber: 103, pokemon: "exegutor" },
    { pokedexNumber: 104, pokemon: "cubone" },
    { pokedexNumber: 105, pokemon: "marowak" },
    { pokedexNumber: 106, pokemon: "hitmonlee" },
    { pokedexNumber: 107, pokemon: "hitmonchan" },
    { pokedexNumber: 108, pokemon: "lickitung" },
    { pokedexNumber: 109, pokemon: "koffing" },
    { pokedexNumber: 110, pokemon: "weezing" },
    { pokedexNumber: 111, pokemon: "rhyhorn" },
    { pokedexNumber: 112, pokemon: "rhydon" },
    { pokedexNumber: 113, pokemon: "chansey" },
    { pokedexNumber: 114, pokemon: "tangela" },
    { pokedexNumber: 115, pokemon: "kangaskhan" },
    { pokedexNumber: 116, pokemon: "horsea" },
    { pokedexNumber: 117, pokemon: "seadra" },
    { pokedexNumber: 118, pokemon: "goldeen" },
    { pokedexNumber: 119, pokemon: "seaking" },
    { pokedexNumber: 120, pokemon: "staryu" },
    { pokedexNumber: 121, pokemon: "starmie" },
    { pokedexNumber: 122, pokemon: "mr. mime" },
    { pokedexNumber: 123, pokemon: "scyther" },
    { pokedexNumber: 124, pokemon: "jynx" },
    { pokedexNumber: 125, pokemon: "electabuzz" },
    { pokedexNumber: 126, pokemon: "magmar" },
    { pokedexNumber: 127, pokemon: "pinsir" },
    { pokedexNumber: 128, pokemon: "tauros" },
    { pokedexNumber: 129, pokemon: "magikarp" },
    { pokedexNumber: 130, pokemon: "gyarados" },
    { pokedexNumber: 131, pokemon: "lapras" },
    { pokedexNumber: 132, pokemon: "ditto" },
    { pokedexNumber: 133, pokemon: "eevee" },
    { pokedexNumber: 134, pokemon: "vaporeon" },
    { pokedexNumber: 135, pokemon: "jolteon" },
    { pokedexNumber: 136, pokemon: "flareon" },
    { pokedexNumber: 137, pokemon: "porygon" },
    { pokedexNumber: 138, pokemon: "omanyte" },
    { pokedexNumber: 139, pokemon: "omastar" },
    { pokedexNumber: 140, pokemon: "kabuto" },
    { pokedexNumber: 141, pokemon: "kabutops" },
    { pokedexNumber: 142, pokemon: "aerodactyl" },
    { pokedexNumber: 143, pokemon: "snorlax" },
    { pokedexNumber: 144, pokemon: "articuno" },
    { pokedexNumber: 145, pokemon: "zapdos" },
    { pokedexNumber: 146, pokemon: "moltres" },
    { pokedexNumber: 147, pokemon: "dratini" },
    { pokedexNumber: 148, pokemon: "dragonair" },
    { pokedexNumber: 149, pokemon: "dragonite" },
    { pokedexNumber: 150, pokemon: "mewtwo" },
    { pokedexNumber: 151, pokemon: "mew" }
];

const gen2 = [
    { pokedexNumber: 152, pokemon: "chikorita" },
    { pokedexNumber: 153, pokemon: "bayleef" },
    { pokedexNumber: 154, pokemon: "meganium" },
    { pokedexNumber: 155, pokemon: "cyndaquil" },
    { pokedexNumber: 156, pokemon: "quilava" },
    { pokedexNumber: 157, pokemon: "typhlosion" },
    { pokedexNumber: 158, pokemon: "totodile" },
    { pokedexNumber: 159, pokemon: "croconaw" },
    { pokedexNumber: 160, pokemon: "feraligatr" },
    { pokedexNumber: 161, pokemon: "sentret" },
    { pokedexNumber: 162, pokemon: "furret" },
    { pokedexNumber: 163, pokemon: "hoothoot" },
    { pokedexNumber: 164, pokemon: "noctowl" },
    { pokedexNumber: 165, pokemon: "ledyba" },
    { pokedexNumber: 166, pokemon: "ledian" },
    { pokedexNumber: 167, pokemon: "spinarak" },
    { pokedexNumber: 168, pokemon: "ariados" },
    { pokedexNumber: 169, pokemon: "crobat" },
    { pokedexNumber: 170, pokemon: "chinchou" },
    { pokedexNumber: 171, pokemon: "lanturn" },
    { pokedexNumber: 172, pokemon: "pichu" },
    { pokedexNumber: 173, pokemon: "cleffa" },
    { pokedexNumber: 174, pokemon: "igglybuff" },
    { pokedexNumber: 175, pokemon: "togepi" },
    { pokedexNumber: 176, pokemon: "togetic" },
    { pokedexNumber: 177, pokemon: "natu" },
    { pokedexNumber: 178, pokemon: "xatu" },
    { pokedexNumber: 179, pokemon: "mareep" },
    { pokedexNumber: 180, pokemon: "flaaffy" },
    { pokedexNumber: 181, pokemon: "ampharos" },
    { pokedexNumber: 182, pokemon: "bellossom" },
    { pokedexNumber: 183, pokemon: "marill" },
    { pokedexNumber: 184, pokemon: "azumarill" },
    { pokedexNumber: 185, pokemon: "sudowoodo" },
    { pokedexNumber: 186, pokemon: "politoed" },
    { pokedexNumber: 187, pokemon: "hoppip" },
    { pokedexNumber: 188, pokemon: "skiploom" },
    { pokedexNumber: 189, pokemon: "jumpluff" },
    { pokedexNumber: 190, pokemon: "aipom" },
    { pokedexNumber: 191, pokemon: "sunkern" },
    { pokedexNumber: 192, pokemon: "sunflora" },
    { pokedexNumber: 193, pokemon: "yanma" },
    { pokedexNumber: 194, pokemon: "wooper" },
    { pokedexNumber: 195, pokemon: "quagsire" },
    { pokedexNumber: 196, pokemon: "espeon" },
    { pokedexNumber: 197, pokemon: "umbreon" },
    { pokedexNumber: 198, pokemon: "murkrow" },
    { pokedexNumber: 199, pokemon: "slowking" },
    { pokedexNumber: 200, pokemon: "misdreavus" },
    { pokedexNumber: 201, pokemon: "unown" },
    { pokedexNumber: 202, pokemon: "wobbuffet" },
    { pokedexNumber: 203, pokemon: "girafarig" },
    { pokedexNumber: 204, pokemon: "pineco" },
    { pokedexNumber: 205, pokemon: "forretress" },
    { pokedexNumber: 206, pokemon: "dunsparce" },
    { pokedexNumber: 207, pokemon: "gligar" },
    { pokedexNumber: 208, pokemon: "steelix" },
    { pokedexNumber: 209, pokemon: "snubbull" },
    { pokedexNumber: 210, pokemon: "granbull" },
    { pokedexNumber: 211, pokemon: "qwilfish" },
    { pokedexNumber: 212, pokemon: "scizor" },
    { pokedexNumber: 213, pokemon: "shuckle" },
    { pokedexNumber: 214, pokemon: "heracross" },
    { pokedexNumber: 215, pokemon: "sneasel" },
    { pokedexNumber: 216, pokemon: "teddiursa" },
    { pokedexNumber: 217, pokemon: "ursaring" },
    { pokedexNumber: 218, pokemon: "slugma" },
    { pokedexNumber: 219, pokemon: "magcargo" },
    { pokedexNumber: 220, pokemon: "swinub" },
    { pokedexNumber: 221, pokemon: "piloswine" },
    { pokedexNumber: 222, pokemon: "corsola" },
    { pokedexNumber: 223, pokemon: "remoraid" },
    { pokedexNumber: 224, pokemon: "octillery" },
    { pokedexNumber: 225, pokemon: "delibird" },
    { pokedexNumber: 226, pokemon: "mantine" },
    { pokedexNumber: 227, pokemon: "skarmory" },
    { pokedexNumber: 228, pokemon: "houndour" },
    { pokedexNumber: 229, pokemon: "houndoom" },
    { pokedexNumber: 230, pokemon: "kingdra" },
    { pokedexNumber: 231, pokemon: "phanpy" },
    { pokedexNumber: 232, pokemon: "donphan" },
    { pokedexNumber: 233, pokemon: "porygon2" },
    { pokedexNumber: 234, pokemon: "stantler" },
    { pokedexNumber: 235, pokemon: "smeargle" },
    { pokedexNumber: 236, pokemon: "tyrogue" },
    { pokedexNumber: 237, pokemon: "hitmontop" },
    { pokedexNumber: 238, pokemon: "smoochum" },
    { pokedexNumber: 239, pokemon: "elekid" },
    { pokedexNumber: 240, pokemon: "magby" },
    { pokedexNumber: 241, pokemon: "miltank" },
    { pokedexNumber: 242, pokemon: "blissey" },
    { pokedexNumber: 243, pokemon: "raikou" },
    { pokedexNumber: 244, pokemon: "entei" },
    { pokedexNumber: 245, pokemon: "suicune" },
    { pokedexNumber: 246, pokemon: "larvitar" },
    { pokedexNumber: 247, pokemon: "pupitar" },
    { pokedexNumber: 248, pokemon: "tyranitar" },
    { pokedexNumber: 249, pokemon: "lugia" },
    { pokedexNumber: 250, pokemon: "ho-oh" },
    { pokedexNumber: 251, pokemon: "celebi" }
];

const gen3 = [
    { pokedexNumber: 252, pokemon: "treecko" },
    { pokedexNumber: 253, pokemon: "groveyle" },
    { pokedexNumber: 254, pokemon: "sceptile" },
    { pokedexNumber: 255, pokemon: "torchic" },
    { pokedexNumber: 256, pokemon: "combusken" },
    { pokedexNumber: 257, pokemon: "blaziken" },
    { pokedexNumber: 258, pokemon: "mudkip" },
    { pokedexNumber: 259, pokemon: "marshtomp" },
    { pokedexNumber: 260, pokemon: "swampert" },
    { pokedexNumber: 261, pokemon: "poochyena" },
    { pokedexNumber: 262, pokemon: "mightyena" },
    { pokedexNumber: 263, pokemon: "zigzagoon" },
    { pokedexNumber: 264, pokemon: "linoone" },
    { pokedexNumber: 265, pokemon: "wurmple" },
    { pokedexNumber: 266, pokemon: "silcoon" },
    { pokedexNumber: 267, pokemon: "beautifly" },
    { pokedexNumber: 268, pokemon: "cascoon" },
    { pokedexNumber: 269, pokemon: "dustox" },
    { pokedexNumber: 270, pokemon: "lotad" },
    { pokedexNumber: 271, pokemon: "lombre" },
    { pokedexNumber: 272, pokemon: "ludicolo" },
    { pokedexNumber: 273, pokemon: "seedot" },
    { pokedexNumber: 274, pokemon: "nuzleaf" },
    { pokedexNumber: 275, pokemon: "shiftry" },
    { pokedexNumber: 276, pokemon: "taillow" },
    { pokedexNumber: 277, pokemon: "swellow" },
    { pokedexNumber: 278, pokemon: "wingull" },
    { pokedexNumber: 279, pokemon: "pelipper" },
    { pokedexNumber: 280, pokemon: "ralts" },
    { pokedexNumber: 281, pokemon: "kirlia" },
    { pokedexNumber: 282, pokemon: "gardevoir" },
    { pokedexNumber: 283, pokemon: "surskit" },
    { pokedexNumber: 284, pokemon: "masqrain" },
    { pokedexNumber: 285, pokemon: "shroomish" },
    { pokedexNumber: 286, pokemon: "breloom" },
    { pokedexNumber: 287, pokemon: "slakoth" },
    { pokedexNumber: 288, pokemon: "vigoroth" },
    { pokedexNumber: 289, pokemon: "slaking" },
    { pokedexNumber: 290, pokemon: "nincada" },
    { pokedexNumber: 291, pokemon: "ninjask" },
    { pokedexNumber: 292, pokemon: "shedinja" },
    { pokedexNumber: 293, pokemon: "whismur" },
    { pokedexNumber: 294, pokemon: "loudred" },
    { pokedexNumber: 295, pokemon: "exploud" },
    { pokedexNumber: 296, pokemon: "makuhita" },
    { pokedexNumber: 297, pokemon: "hariyama" },
    { pokedexNumber: 298, pokemon: "azurill" },
    { pokedexNumber: 299, pokemon: "nosepass" },
    { pokedexNumber: 300, pokemon: "skitty" },
    { pokedexNumber: 301, pokemon: "delcatty" },
    { pokedexNumber: 302, pokemon: "sableye" },
    { pokedexNumber: 303, pokemon: "mawile" },
    { pokedexNumber: 304, pokemon: "aron" },
    { pokedexNumber: 305, pokemon: "lairon" },
    { pokedexNumber: 306, pokemon: "aggron" },
    { pokedexNumber: 307, pokemon: "meditite" },
    { pokedexNumber: 308, pokemon: "medicham" },
    { pokedexNumber: 309, pokemon: "electrike" },
    { pokedexNumber: 310, pokemon: "manectric" },
    { pokedexNumber: 311, pokemon: "plusle" },
    { pokedexNumber: 312, pokemon: "minun" },
    { pokedexNumber: 313, pokemon: "volbeat" },
    { pokedexNumber: 314, pokemon: "illumise" },
    { pokedexNumber: 315, pokemon: "roselia" },
    { pokedexNumber: 316, pokemon: "gulpin" },
    { pokedexNumber: 317, pokemon: "swalot" },
    { pokedexNumber: 318, pokemon: "carvanha" },
    { pokedexNumber: 319, pokemon: "sharpedo" },
    { pokedexNumber: 320, pokemon: "wailmer" },
    { pokedexNumber: 321, pokemon: "wailord" },
    { pokedexNumber: 322, pokemon: "numel" },
    { pokedexNumber: 323, pokemon: "camerupt" },
    { pokedexNumber: 324, pokemon: "torkoal" },
    { pokedexNumber: 325, pokemon: "spoink" },
    { pokedexNumber: 326, pokemon: "grumpig" },
    { pokedexNumber: 327, pokemon: "spinda" },
    { pokedexNumber: 328, pokemon: "trapinch" },
    { pokedexNumber: 329, pokemon: "vibrava" },
    { pokedexNumber: 330, pokemon: "flygon" },
    { pokedexNumber: 331, pokemon: "cacnea" },
    { pokedexNumber: 332, pokemon: "cacturne" },
    { pokedexNumber: 333, pokemon: "swablu" },
    { pokedexNumber: 334, pokemon: "altaria" },
    { pokedexNumber: 335, pokemon: "zangoose" },
    { pokedexNumber: 336, pokemon: "seviper" },
    { pokedexNumber: 337, pokemon: "lunatone" },
    { pokedexNumber: 338, pokemon: "solrock" },
    { pokedexNumber: 339, pokemon: "barboach" },
    { pokedexNumber: 340, pokemon: "whiscash" },
    { pokedexNumber: 341, pokemon: "corphish" },
    { pokedexNumber: 342, pokemon: "crawdaunt" },
    { pokedexNumber: 343, pokemon: "baltoy" },
    { pokedexNumber: 344, pokemon: "claydol" },
    { pokedexNumber: 345, pokemon: "lileep" },
    { pokedexNumber: 346, pokemon: "cradily" },
    { pokedexNumber: 347, pokemon: "anorith" },
    { pokedexNumber: 348, pokemon: "armaldo" },
    { pokedexNumber: 349, pokemon: "feebas" },
    { pokedexNumber: 350, pokemon: "milotic" },
    { pokedexNumber: 351, pokemon: "castform" },
    { pokedexNumber: 352, pokemon: "kecleon" },
    { pokedexNumber: 353, pokemon: "shuppet" },
    { pokedexNumber: 354, pokemon: "banette" },
    { pokedexNumber: 355, pokemon: "duskull" },
    { pokedexNumber: 356, pokemon: "dusclops" },
    { pokedexNumber: 357, pokemon: "tropius" },
    { pokedexNumber: 358, pokemon: "chimecho" },
    { pokedexNumber: 359, pokemon: "absol" },
    { pokedexNumber: 360, pokemon: "wynaut" },
    { pokedexNumber: 361, pokemon: "snorunt" },
    { pokedexNumber: 362, pokemon: "glalie" },
    { pokedexNumber: 363, pokemon: "spheal" },
    { pokedexNumber: 364, pokemon: "sealeo" },
    { pokedexNumber: 365, pokemon: "walrein" },
    { pokedexNumber: 366, pokemon: "clamperl" },
    { pokedexNumber: 367, pokemon: "huntail" },
    { pokedexNumber: 368, pokemon: "gorebyss" },
    { pokedexNumber: 369, pokemon: "relicanth" },
    { pokedexNumber: 370, pokemon: "luvdisc" },
    { pokedexNumber: 371, pokemon: "bagon" },
    { pokedexNumber: 372, pokemon: "shelgon" },
    { pokedexNumber: 373, pokemon: "salamence" },
    { pokedexNumber: 374, pokemon: "beldum" },
    { pokedexNumber: 375, pokemon: "metang" },
    { pokedexNumber: 376, pokemon: "metagross" },
    { pokedexNumber: 377, pokemon: "regirock" },
    { pokedexNumber: 378, pokemon: "regice" },
    { pokedexNumber: 379, pokemon: "registeel" },
    { pokedexNumber: 380, pokemon: "latias" },
    { pokedexNumber: 381, pokemon: "latios" },
    { pokedexNumber: 382, pokemon: "kyogre" },
    { pokedexNumber: 383, pokemon: "groudon" },
    { pokedexNumber: 384, pokemon: "rayquaza" },
    { pokedexNumber: 385, pokemon: "jirachi" },
    { pokedexNumber: 386, pokemon: "deoxys" }
];

const gen4 = [
    { pokedexNumber: 387, pokemon: "turtwig" },
    { pokedexNumber: 388, pokemon: "grotle" },
    { pokedexNumber: 389, pokemon: "torterra" },
    { pokedexNumber: 390, pokemon: "chimchar" },
    { pokedexNumber: 391, pokemon: "monferno" },
    { pokedexNumber: 392, pokemon: "infernape" },
    { pokedexNumber: 393, pokemon: "piplup" },
    { pokedexNumber: 394, pokemon: "prinplup" },
    { pokedexNumber: 395, pokemon: "empoleon" },
    { pokedexNumber: 396, pokemon: "starly" },
    { pokedexNumber: 397, pokemon: "staravia" },
    { pokedexNumber: 398, pokemon: "staraptor" },
    { pokedexNumber: 399, pokemon: "bidoof" },
    { pokedexNumber: 400, pokemon: "bibarel" },
    { pokedexNumber: 401, pokemon: "kricketot" },
    { pokedexNumber: 402, pokemon: "kricketune" },
    { pokedexNumber: 403, pokemon: "shinx" },
    { pokedexNumber: 404, pokemon: "luxio" },
    { pokedexNumber: 405, pokemon: "luxray" },
    { pokedexNumber: 406, pokemon: "budew" },
    { pokedexNumber: 407, pokemon: "roserade" },
    { pokedexNumber: 408, pokemon: "cranidos" },
    { pokedexNumber: 409, pokemon: "rampardos" },
    { pokedexNumber: 410, pokemon: "shieldon" },
    { pokedexNumber: 411, pokemon: "bastiodon" },
    { pokedexNumber: 412, pokemon: "burmy" },
    { pokedexNumber: 413, pokemon: "wormadam" },
    { pokedexNumber: 414, pokemon: "mothim" },
    { pokedexNumber: 415, pokemon: "combee" },
    { pokedexNumber: 416, pokemon: "vespiquen" },
    { pokedexNumber: 417, pokemon: "pachirisu" },
    { pokedexNumber: 418, pokemon: "buizel" },
    { pokedexNumber: 419, pokemon: "floatzel" },
    { pokedexNumber: 420, pokemon: "cherubi" },
    { pokedexNumber: 421, pokemon: "cherrim" },
    { pokedexNumber: 422, pokemon: "shellos" },
    { pokedexNumber: 423, pokemon: "gastrodon" },
    { pokedexNumber: 424, pokemon: "ambipom" },
    { pokedexNumber: 425, pokemon: "drifloon" },
    { pokedexNumber: 426, pokemon: "drifblim" },
    { pokedexNumber: 427, pokemon: "buneary" },
    { pokedexNumber: 428, pokemon: "lopunny" },
    { pokedexNumber: 429, pokemon: "mismagius" },
    { pokedexNumber: 430, pokemon: "honchkrow" },
    { pokedexNumber: 431, pokemon: "glameow" },
    { pokedexNumber: 432, pokemon: "purugly" },
    { pokedexNumber: 433, pokemon: "chingling" },
    { pokedexNumber: 434, pokemon: "stunky" },
    { pokedexNumber: 435, pokemon: "skuntank" },
    { pokedexNumber: 436, pokemon: "bronzor" },
    { pokedexNumber: 437, pokemon: "bronzong" },
    { pokedexNumber: 438, pokemon: "bonsly" },
    { pokedexNumber: 439, pokemon: "mime jr" },
    { pokedexNumber: 440, pokemon: "happiny" },
    { pokedexNumber: 441, pokemon: "chatot" },
    { pokedexNumber: 442, pokemon: "spiritomb" },
    { pokedexNumber: 443, pokemon: "gible" },
    { pokedexNumber: 444, pokemon: "gabite" },
    { pokedexNumber: 445, pokemon: "garchomp" },
    { pokedexNumber: 446, pokemon: "munchlax" },
    { pokedexNumber: 447, pokemon: "riolu" },
    { pokedexNumber: 448, pokemon: "lucario" },
    { pokedexNumber: 449, pokemon: "hippopotas" },
    { pokedexNumber: 450, pokemon: "hippowdon" },
    { pokedexNumber: 451, pokemon: "skorupi" },
    { pokedexNumber: 452, pokemon: "drapion" },
    { pokedexNumber: 453, pokemon: "croagunk" },
    { pokedexNumber: 454, pokemon: "toxicroak" },
    { pokedexNumber: 455, pokemon: "carnivine" },
    { pokedexNumber: 456, pokemon: "finneon" },
    { pokedexNumber: 457, pokemon: "lumineon" },
    { pokedexNumber: 458, pokemon: "mantyke" },
    { pokedexNumber: 459, pokemon: "snover" },
    { pokedexNumber: 460, pokemon: "abomasnow" },
    { pokedexNumber: 461, pokemon: "weavile" },
    { pokedexNumber: 462, pokemon: "magnezone" },
    { pokedexNumber: 463, pokemon: "lickilicky" },
    { pokedexNumber: 464, pokemon: "rhyperior" },
    { pokedexNumber: 465, pokemon: "tangrowth" },
    { pokedexNumber: 466, pokemon: "electivire" },
    { pokedexNumber: 467, pokemon: "magmortar" },
    { pokedexNumber: 468, pokemon: "togekiss" },
    { pokedexNumber: 469, pokemon: "yanmega" },
    { pokedexNumber: 470, pokemon: "leafeon" },
    { pokedexNumber: 471, pokemon: "glaceon" },
    { pokedexNumber: 472, pokemon: "gliscor" },
    { pokedexNumber: 473, pokemon: "mamoswine" },
    { pokedexNumber: 474, pokemon: "porygonz" },
    { pokedexNumber: 475, pokemon: "gallade" },
    { pokedexNumber: 476, pokemon: "probopass" },
    { pokedexNumber: 477, pokemon: "dusknoir" },
    { pokedexNumber: 478, pokemon: "froslass" },
    { pokedexNumber: 479, pokemon: "rotom" },
    { pokedexNumber: 480, pokemon: "uxie" },
    { pokedexNumber: 481, pokemon: "mesprit" },
    { pokedexNumber: 482, pokemon: "azelf" },
    { pokedexNumber: 483, pokemon: "dialga" },
    { pokedexNumber: 484, pokemon: "palkia" },
    { pokedexNumber: 485, pokemon: "heatran" },
    { pokedexNumber: 486, pokemon: "regigigas" },
    { pokedexNumber: 487, pokemon: "giratina" },
    { pokedexNumber: 488, pokemon: "cresselia" },
    { pokedexNumber: 489, pokemon: "phione" },
    { pokedexNumber: 490, pokemon: "manaphy" },
    { pokedexNumber: 491, pokemon: "darkrai" },
    { pokedexNumber: 492, pokemon: "shaymin" },
    { pokedexNumber: 493, pokemon: "arceus" },
];

const gen5 = [
    { pokedexNumber: 494, pokemon: "victini" },
    { pokedexNumber: 495, pokemon: "snivy" },
    { pokedexNumber: 496, pokemon: "servine" },
    { pokedexNumber: 497, pokemon: "serperior" },
    { pokedexNumber: 498, pokemon: "tepig" },
    { pokedexNumber: 499, pokemon: "pignite" },
    { pokedexNumber: 500, pokemon: "emboar" },
    { pokedexNumber: 501, pokemon: "oshawott" },
    { pokedexNumber: 502, pokemon: "dewott" },
    { pokedexNumber: 503, pokemon: "samurott" },
    { pokedexNumber: 504, pokemon: "patrat" },
    { pokedexNumber: 505, pokemon: "watchog" },
    { pokedexNumber: 506, pokemon: "lillipup" },
    { pokedexNumber: 507, pokemon: "herdier" },
    { pokedexNumber: 508, pokemon: "stoutland" },
    { pokedexNumber: 509, pokemon: "purrloin" },
    { pokedexNumber: 510, pokemon: "liepard" },
    { pokedexNumber: 511, pokemon: "pansage" },
    { pokedexNumber: 512, pokemon: "simisage" },
    { pokedexNumber: 513, pokemon: "pansear" },
    { pokedexNumber: 514, pokemon: "simisear" },
    { pokedexNumber: 515, pokemon: "panpour" },
    { pokedexNumber: 516, pokemon: "simipour" },
    { pokedexNumber: 517, pokemon: "munna" },
    { pokedexNumber: 518, pokemon: "musharna" },
    { pokedexNumber: 519, pokemon: "pidove" },
    { pokedexNumber: 520, pokemon: "tranquill" },
    { pokedexNumber: 521, pokemon: "unfezant" },
    { pokedexNumber: 522, pokemon: "blitzle" },
    { pokedexNumber: 523, pokemon: "zebstrika" },
    { pokedexNumber: 524, pokemon: "roggenrola" },
    { pokedexNumber: 525, pokemon: "boldore" },
    { pokedexNumber: 526, pokemon: "gigalith" },
    { pokedexNumber: 527, pokemon: "woobat" },
    { pokedexNumber: 528, pokemon: "swoobat" },
    { pokedexNumber: 529, pokemon: "drilbur" },
    { pokedexNumber: 530, pokemon: "excadrill" },
    { pokedexNumber: 531, pokemon: "audino" },
    { pokedexNumber: 532, pokemon: "timburr" },
    { pokedexNumber: 533, pokemon: "gurdurr" },
    { pokedexNumber: 534, pokemon: "conkeldurr" },
    { pokedexNumber: 535, pokemon: "tympole" },
    { pokedexNumber: 536, pokemon: "palpitoad" },
    { pokedexNumber: 537, pokemon: "seismitoad" },
    { pokedexNumber: 538, pokemon: "throh" },
    { pokedexNumber: 539, pokemon: "sawk" },
    { pokedexNumber: 540, pokemon: "sewaddle" },
    { pokedexNumber: 541, pokemon: "swadloon" },
    { pokedexNumber: 542, pokemon: "leavanny" },
    { pokedexNumber: 543, pokemon: "venipede" },
    { pokedexNumber: 544, pokemon: "whirlipede" },
    { pokedexNumber: 545, pokemon: "scolipede" },
    { pokedexNumber: 546, pokemon: "cottonee" },
    { pokedexNumber: 547, pokemon: "whimsicott" },
    { pokedexNumber: 548, pokemon: "petilil" },
    { pokedexNumber: 549, pokemon: "lilligant" },
    { pokedexNumber: 550, pokemon: "basculin" },
    { pokedexNumber: 551, pokemon: "sandile" },
    { pokedexNumber: 552, pokemon: "krokorok" },
    { pokedexNumber: 553, pokemon: "krookodile" },
    { pokedexNumber: 554, pokemon: "darumaka" },
    { pokedexNumber: 555, pokemon: "darmanitan" },
    { pokedexNumber: 556, pokemon: "maractus" },
    { pokedexNumber: 557, pokemon: "dwebble" },
    { pokedexNumber: 558, pokemon: "crustle" },
    { pokedexNumber: 559, pokemon: "scraggy" },
    { pokedexNumber: 560, pokemon: "scrafty" },
    { pokedexNumber: 561, pokemon: "sigilyph" },
    { pokedexNumber: 562, pokemon: "yamask" },
    { pokedexNumber: 563, pokemon: "cofagrigus" },
    { pokedexNumber: 564, pokemon: "tirtouga" },
    { pokedexNumber: 565, pokemon: "carracosta" },
    { pokedexNumber: 566, pokemon: "archen" },
    { pokedexNumber: 567, pokemon: "archeops" },
    { pokedexNumber: 568, pokemon: "trubbish" },
    { pokedexNumber: 569, pokemon: "garbodor" },
    { pokedexNumber: 570, pokemon: "zorua" },
    { pokedexNumber: 571, pokemon: "zoroark" },
    { pokedexNumber: 572, pokemon: "minccino" },
    { pokedexNumber: 573, pokemon: "cinccino" },
    { pokedexNumber: 574, pokemon: "gothita" },
    { pokedexNumber: 575, pokemon: "gothorita" },
    { pokedexNumber: 576, pokemon: "gothitelle" },
    { pokedexNumber: 577, pokemon: "solosis" },
    { pokedexNumber: 578, pokemon: "duosion" },
    { pokedexNumber: 579, pokemon: "reuniclus" },
    { pokedexNumber: 580, pokemon: "ducklett" },
    { pokedexNumber: 581, pokemon: "swanna" },
    { pokedexNumber: 582, pokemon: "vanillite" },
    { pokedexNumber: 583, pokemon: "vanillish" },
    { pokedexNumber: 584, pokemon: "vanilluxe" },
    { pokedexNumber: 585, pokemon: "deerling" },
    { pokedexNumber: 586, pokemon: "sawsbuck" },
    { pokedexNumber: 587, pokemon: "emolga" },
    { pokedexNumber: 588, pokemon: "karrablast" },
    { pokedexNumber: 589, pokemon: "escavalier" },
    { pokedexNumber: 590, pokemon: "foongus" },
    { pokedexNumber: 591, pokemon: "amoonguss" },
    { pokedexNumber: 592, pokemon: "frillish" },
    { pokedexNumber: 593, pokemon: "jellicent" },
    { pokedexNumber: 594, pokemon: "alomomola" },
    { pokedexNumber: 595, pokemon: "joltik" },
    { pokedexNumber: 596, pokemon: "galvantula" },
    { pokedexNumber: 597, pokemon: "ferroseed" },
    { pokedexNumber: 598, pokemon: "ferrothorn" },
    { pokedexNumber: 599, pokemon: "klink" },
    { pokedexNumber: 600, pokemon: "klang" },
    { pokedexNumber: 601, pokemon: "klinklang" },
    { pokedexNumber: 602, pokemon: "tynamo" },
    { pokedexNumber: 603, pokemon: "eelektrik" },
    { pokedexNumber: 604, pokemon: "eelektross" },
    { pokedexNumber: 605, pokemon: "elgyem" },
    { pokedexNumber: 606, pokemon: "beheeyem" },
    { pokedexNumber: 607, pokemon: "litwick" },
    { pokedexNumber: 608, pokemon: "lampent" },
    { pokedexNumber: 609, pokemon: "chandelure" },
    { pokedexNumber: 610, pokemon: "axew" },
    { pokedexNumber: 611, pokemon: "fraxure" },
    { pokedexNumber: 612, pokemon: "haxorus" },
    { pokedexNumber: 613, pokemon: "cubchoo" },
    { pokedexNumber: 614, pokemon: "beartic" },
    { pokedexNumber: 615, pokemon: "cryogonal" },
    { pokedexNumber: 616, pokemon: "shelmet" },
    { pokedexNumber: 617, pokemon: "accelgor" },
    { pokedexNumber: 618, pokemon: "stunfisk" },
    { pokedexNumber: 619, pokemon: "mienfoo" },
    { pokedexNumber: 620, pokemon: "mienshao" },
    { pokedexNumber: 621, pokemon: "druddigon" },
    { pokedexNumber: 622, pokemon: "golett" },
    { pokedexNumber: 623, pokemon: "golurk" },
    { pokedexNumber: 624, pokemon: "pawniard" },
    { pokedexNumber: 625, pokemon: "bisharp" },
    { pokedexNumber: 626, pokemon: "bouffalant" },
    { pokedexNumber: 627, pokemon: "rufflet" },
    { pokedexNumber: 628, pokemon: "braviary" },
    { pokedexNumber: 629, pokemon: "vullaby" },
    { pokedexNumber: 630, pokemon: "mandibuzz" },
    { pokedexNumber: 631, pokemon: "heatmor" },
    { pokedexNumber: 632, pokemon: "durant" },
    { pokedexNumber: 633, pokemon: "deino" },
    { pokedexNumber: 634, pokemon: "zweilous" },
    { pokedexNumber: 635, pokemon: "hydreigon" },
    { pokedexNumber: 636, pokemon: "larvesta" },
    { pokedexNumber: 637, pokemon: "volcarona" },
    { pokedexNumber: 638, pokemon: "cobalion" },
    { pokedexNumber: 639, pokemon: "terrakion" },
    { pokedexNumber: 640, pokemon: "virizion" },
    { pokedexNumber: 641, pokemon: "tornadus" },
    { pokedexNumber: 642, pokemon: "thundurus" },
    { pokedexNumber: 643, pokemon: "reshiram" },
    { pokedexNumber: 644, pokemon: "zekrom" },
    { pokedexNumber: 645, pokemon: "landorus" },
    { pokedexNumber: 646, pokemon: "kyurem" },
    { pokedexNumber: 647, pokemon: "keldeo" },
    { pokedexNumber: 648, pokemon: "meloetta" },
    { pokedexNumber: 649, pokemon: "genesect" }
];

const gen6 = [
    { pokedexNumber: 650, pokemon: "chespin" },
    { pokedexNumber: 651, pokemon: "quilladin" },
    { pokedexNumber: 652, pokemon: "chesnaught" },
    { pokedexNumber: 653, pokemon: "fennekin" },
    { pokedexNumber: 654, pokemon: "braixen" },
    { pokedexNumber: 655, pokemon: "delphox" },
    { pokedexNumber: 656, pokemon: "froakie" },
    { pokedexNumber: 657, pokemon: "frogadier" },
    { pokedexNumber: 658, pokemon: "greninja" },
    { pokedexNumber: 659, pokemon: "bunnelby" },
    { pokedexNumber: 660, pokemon: "diggersby" },
    { pokedexNumber: 661, pokemon: "fletchling" },
    { pokedexNumber: 662, pokemon: "fletchinder" },
    { pokedexNumber: 663, pokemon: "talonflame" },
    { pokedexNumber: 664, pokemon: "scatterbug" },
    { pokedexNumber: 665, pokemon: "spewpa" },
    { pokedexNumber: 666, pokemon: "vivillon" },
    { pokedexNumber: 667, pokemon: "litleo" },
    { pokedexNumber: 668, pokemon: "pyroar" },
    { pokedexNumber: 669, pokemon: "flabebe" },
    { pokedexNumber: 670, pokemon: "floette" },
    { pokedexNumber: 671, pokemon: "florges" },
    { pokedexNumber: 672, pokemon: "skiddo" },
    { pokedexNumber: 673, pokemon: "gogoat" },
    { pokedexNumber: 674, pokemon: "pancham" },
    { pokedexNumber: 675, pokemon: "pangoro" },
    { pokedexNumber: 676, pokemon: "furfrou" },
    { pokedexNumber: 677, pokemon: "espurr" },
    { pokedexNumber: 678, pokemon: "meowstic" },
    { pokedexNumber: 679, pokemon: "honedge" },
    { pokedexNumber: 680, pokemon: "doublade" },
    { pokedexNumber: 681, pokemon: "aegislash" },
    { pokedexNumber: 682, pokemon: "spritzee" },
    { pokedexNumber: 683, pokemon: "aromatisse" },
    { pokedexNumber: 684, pokemon: "swirlix" },
    { pokedexNumber: 685, pokemon: "slurpuff" },
    { pokedexNumber: 686, pokemon: "inkay" },
    { pokedexNumber: 687, pokemon: "malamar" },
    { pokedexNumber: 688, pokemon: "binacle" },
    { pokedexNumber: 689, pokemon: "barbaracle" },
    { pokedexNumber: 690, pokemon: "skrelp" },
    { pokedexNumber: 691, pokemon: "dragalge" },
    { pokedexNumber: 692, pokemon: "clauncher" },
    { pokedexNumber: 693, pokemon: "clawitzer" },
    { pokedexNumber: 694, pokemon: "helioptile" },
    { pokedexNumber: 695, pokemon: "heliolisk" },
    { pokedexNumber: 696, pokemon: "tyrunt" },
    { pokedexNumber: 697, pokemon: "tyrantrum" },
    { pokedexNumber: 698, pokemon: "amaura" },
    { pokedexNumber: 699, pokemon: "aurorus" },
    { pokedexNumber: 700, pokemon: "sylveon" },
    { pokedexNumber: 701, pokemon: "hawlucha" },
    { pokedexNumber: 702, pokemon: "dedenne" },
    { pokedexNumber: 703, pokemon: "carbink" },
    { pokedexNumber: 704, pokemon: "goomy" },
    { pokedexNumber: 705, pokemon: "sliggoo" },
    { pokedexNumber: 706, pokemon: "goodra" },
    { pokedexNumber: 707, pokemon: "klefki" },
    { pokedexNumber: 708, pokemon: "phantump" },
    { pokedexNumber: 709, pokemon: "trevenant" },
    { pokedexNumber: 710, pokemon: "pumpkaboo" },
    { pokedexNumber: 711, pokemon: "gourgeist" },
    { pokedexNumber: 712, pokemon: "bergmite" },
    { pokedexNumber: 713, pokemon: "avalugg" },
    { pokedexNumber: 714, pokemon: "noibat" },
    { pokedexNumber: 715, pokemon: "noivern" },
    { pokedexNumber: 716, pokemon: "xerneas" },
    { pokedexNumber: 717, pokemon: "yveltal" },
    { pokedexNumber: 718, pokemon: "zygarde" },
    { pokedexNumber: 719, pokemon: "diancie" },
    { pokedexNumber: 720, pokemon: "hoopa" },
    { pokedexNumber: 721, pokemon: "volcanion" }
];

const gen7 = [
    { pokedexNumber: 722, pokemon: "rowlet" },
    { pokedexNumber: 723, pokemon: "dartrix" },
    { pokedexNumber: 724, pokemon: "decidueye" },
    { pokedexNumber: 725, pokemon: "litten" },
    { pokedexNumber: 726, pokemon: "torracat" },
    { pokedexNumber: 727, pokemon: "incineroar" },
    { pokedexNumber: 728, pokemon: "popplio" },
    { pokedexNumber: 729, pokemon: "brionne" },
    { pokedexNumber: 730, pokemon: "primarina" },
    { pokedexNumber: 731, pokemon: "pikipek" },
    { pokedexNumber: 732, pokemon: "trumbeak" },
    { pokedexNumber: 733, pokemon: "toucannon" },
    { pokedexNumber: 734, pokemon: "yungoos" },
    { pokedexNumber: 735, pokemon: "gumshoos" },
    { pokedexNumber: 736, pokemon: "grubbin" },
    { pokedexNumber: 737, pokemon: "charjabug" },
    { pokedexNumber: 738, pokemon: "vikavolt" },
    { pokedexNumber: 739, pokemon: "crabrawler" },
    { pokedexNumber: 740, pokemon: "crabominable" },
    { pokedexNumber: 741, pokemon: "oricorio" },
    { pokedexNumber: 742, pokemon: "cutiefly" },
    { pokedexNumber: 743, pokemon: "ribombee" },
    { pokedexNumber: 744, pokemon: "rockruff" },
    { pokedexNumber: 745, pokemon: "lycanroc" },
    { pokedexNumber: 746, pokemon: "wishiwashi" },
    { pokedexNumber: 747, pokemon: "mareanie" },
    { pokedexNumber: 748, pokemon: "toxapex" },
    { pokedexNumber: 749, pokemon: "mudbray" },
    { pokedexNumber: 750, pokemon: "mudsdale" },
    { pokedexNumber: 751, pokemon: "dewpider" },
    { pokedexNumber: 752, pokemon: "araquanid" },
    { pokedexNumber: 753, pokemon: "fomantis" },
    { pokedexNumber: 754, pokemon: "lurantis" },
    { pokedexNumber: 755, pokemon: "morelull" },
    { pokedexNumber: 756, pokemon: "shiinotic" },
    { pokedexNumber: 757, pokemon: "salandit" },
    { pokedexNumber: 758, pokemon: "salazzle" },
    { pokedexNumber: 759, pokemon: "stufful" },
    { pokedexNumber: 760, pokemon: "bewear" },
    { pokedexNumber: 761, pokemon: "bounsweet" },
    { pokedexNumber: 762, pokemon: "steenee" },
    { pokedexNumber: 763, pokemon: "tsareena" },
    { pokedexNumber: 764, pokemon: "comfey" },
    { pokedexNumber: 765, pokemon: "oranguru" },
    { pokedexNumber: 766, pokemon: "passimian" },
    { pokedexNumber: 767, pokemon: "wimpod" },
    { pokedexNumber: 768, pokemon: "golisopod" },
    { pokedexNumber: 769, pokemon: "sandygast" },
    { pokedexNumber: 770, pokemon: "palossand" },
    { pokedexNumber: 771, pokemon: "pyukumuku" },
    { pokedexNumber: 772, pokemon: "type: null" },
    { pokedexNumber: 773, pokemon: "silvally" },
    { pokedexNumber: 774, pokemon: "minior" },
    { pokedexNumber: 775, pokemon: "komala" },
    { pokedexNumber: 776, pokemon: "turtonator" },
    { pokedexNumber: 777, pokemon: "togedemaru" },
    { pokedexNumber: 778, pokemon: "mimikyu" },
    { pokedexNumber: 779, pokemon: "bruxish" },
    { pokedexNumber: 780, pokemon: "drampa" },
    { pokedexNumber: 781, pokemon: "dhelmise" },
    { pokedexNumber: 782, pokemon: "jangmo-o" },
    { pokedexNumber: 783, pokemon: "hakamo-o" },
    { pokedexNumber: 784, pokemon: "kommo-o" },
    { pokedexNumber: 785, pokemon: "tapu koko" },
    { pokedexNumber: 786, pokemon: "tapu lele" },
    { pokedexNumber: 787, pokemon: "tapu bulu" },
    { pokedexNumber: 788, pokemon: "tapu fini" },
    { pokedexNumber: 789, pokemon: "cosmog" },
    { pokedexNumber: 790, pokemon: "cosmoem" },
    { pokedexNumber: 791, pokemon: "solgaleo" },
    { pokedexNumber: 792, pokemon: "lunala" },
    { pokedexNumber: 793, pokemon: "nihilego" },
    { pokedexNumber: 794, pokemon: "buzzwole" },
    { pokedexNumber: 795, pokemon: "pheromosa" },
    { pokedexNumber: 796, pokemon: "xurkitree" },
    { pokedexNumber: 797, pokemon: "celesteela" },
    { pokedexNumber: 798, pokemon: "kartana" },
    { pokedexNumber: 799, pokemon: "guzzlord" },
    { pokedexNumber: 800, pokemon: "necrozma" },
    { pokedexNumber: 801, pokemon: "magearna" },
    { pokedexNumber: 802, pokemon: "marshadow" },
    { pokedexNumber: 803, pokemon: "poipole" },
    { pokedexNumber: 804, pokemon: "naganadel" },
    { pokedexNumber: 805, pokemon: "stakataka" },
    { pokedexNumber: 806, pokemon: "blacephalon" },
    { pokedexNumber: 807, pokemon: "zeraora" },
    { pokedexNumber: 808, pokemon: "meltan" },
    { pokedexNumber: 809, pokemon: "melmetal" }
];

const gen8 = [
    { pokedexNumber: 810, pokemon: "grookey" },
    { pokedexNumber: 811, pokemon: "thwackey" },
    { pokedexNumber: 812, pokemon: "rillaboom" },
    { pokedexNumber: 813, pokemon: "scorbunny" },
    { pokedexNumber: 814, pokemon: "raboot" },
    { pokedexNumber: 815, pokemon: "cinderace" },
    { pokedexNumber: 816, pokemon: "sobble" },
    { pokedexNumber: 817, pokemon: "drizzile" },
    { pokedexNumber: 818, pokemon: "inteleon" },
    { pokedexNumber: 819, pokemon: "skwovet" },
    { pokedexNumber: 820, pokemon: "greedent" },
    { pokedexNumber: 821, pokemon: "rookidee" },
    { pokedexNumber: 822, pokemon: "corvisquire" },
    { pokedexNumber: 823, pokemon: "corviknight" },
    { pokedexNumber: 824, pokemon: "blipbug" },
    { pokedexNumber: 825, pokemon: "dottler" },
    { pokedexNumber: 826, pokemon: "orbeetle" },
    { pokedexNumber: 827, pokemon: "nickit" },
    { pokedexNumber: 828, pokemon: "thievul" },
    { pokedexNumber: 829, pokemon: "gossifleur" },
    { pokedexNumber: 830, pokemon: "eldegoss" },
    { pokedexNumber: 831, pokemon: "wooloo" },
    { pokedexNumber: 832, pokemon: "dubwool" },
    { pokedexNumber: 833, pokemon: "chewtle" },
    { pokedexNumber: 834, pokemon: "drednaw" },
    { pokedexNumber: 835, pokemon: "yamper" },
    { pokedexNumber: 836, pokemon: "boltund" },
    { pokedexNumber: 837, pokemon: "rolycoly" },
    { pokedexNumber: 838, pokemon: "carkol" },
    { pokedexNumber: 839, pokemon: "coalossal" },
    { pokedexNumber: 840, pokemon: "applin" },
    { pokedexNumber: 841, pokemon: "flapple" },
    { pokedexNumber: 842, pokemon: "appletun" },
    { pokedexNumber: 843, pokemon: "silicobra" },
    { pokedexNumber: 844, pokemon: "sandaconda" },
    { pokedexNumber: 845, pokemon: "cramorant" },
    { pokedexNumber: 846, pokemon: "arrokuda" },
    { pokedexNumber: 847, pokemon: "barraskewda" },
    { pokedexNumber: 848, pokemon: "toxels" },
    { pokedexNumber: 849, pokemon: "toxtricity" },
    { pokedexNumber: 850, pokemon: "sizzlipede" },
    { pokedexNumber: 851, pokemon: "centiskorch" },
    { pokedexNumber: 852, pokemon: "clobbopus" },
    { pokedexNumber: 853, pokemon: "grapploct" },
    { pokedexNumber: 854, pokemon: "sinistea" },
    { pokedexNumber: 855, pokemon: "polteageist" },
    { pokedexNumber: 856, pokemon: "hatenna" },
    { pokedexNumber: 857, pokemon: "hattrem" },
    { pokedexNumber: 858, pokemon: "hatterene" },
    { pokedexNumber: 859, pokemon: "impidimp" },
    { pokedexNumber: 860, pokemon: "morgrem" },
    { pokedexNumber: 861, pokemon: "grimmsnarl" },
    { pokedexNumber: 862, pokemon: "obstagoon" },
    { pokedexNumber: 863, pokemon: "perrserker" },
    { pokedexNumber: 864, pokemon: "cursola" },
    { pokedexNumber: 865, pokemon: "sirfetch'd" },
    { pokedexNumber: 866, pokemon: "mr. rime" },
    { pokedexNumber: 867, pokemon: "runerigus" },
    { pokedexNumber: 868, pokemon: "milcery" },
    { pokedexNumber: 869, pokemon: "alcremie" },
    { pokedexNumber: 870, pokemon: "falinks" },
    { pokedexNumber: 871, pokemon: "pincurchin" },
    { pokedexNumber: 872, pokemon: "snom" },
    { pokedexNumber: 873, pokemon: "frosmoth" },
    { pokedexNumber: 874, pokemon: "stonjourner" },
    { pokedexNumber: 875, pokemon: "eiscue" },
    { pokedexNumber: 876, pokemon: "indeedee" },
    { pokedexNumber: 877, pokemon: "morpeko" },
    { pokedexNumber: 878, pokemon: "cufant" },
    { pokedexNumber: 879, pokemon: "copperajah" },
    { pokedexNumber: 880, pokemon: "dracozolt" },
    { pokedexNumber: 881, pokemon: "arctozolt" },
    { pokedexNumber: 882, pokemon: "dracovish" },
    { pokedexNumber: 883, pokemon: "arctovish" },
    { pokedexNumber: 884, pokemon: "duraludon" },
    { pokedexNumber: 885, pokemon: "dreepy" },
    { pokedexNumber: 886, pokemon: "drakloak" },
    { pokedexNumber: 887, pokemon: "dragapult" },
    { pokedexNumber: 888, pokemon: "zacian" },
    { pokedexNumber: 889, pokemon: "zamazenta" },
    { pokedexNumber: 890, pokemon: "eternatus" },
    { pokedexNumber: 891, pokemon: "kubfu" },
    { pokedexNumber: 892, pokemon: "urshifu" },
    { pokedexNumber: 893, pokemon: "zarude" },
    { pokedexNumber: 894, pokemon: "regieleki" },
    { pokedexNumber: 895, pokemon: "regidrago" },
    { pokedexNumber: 896, pokemon: "glastrier" },
    { pokedexNumber: 897, pokemon: "spectrier" },
    { pokedexNumber: 898, pokemon: "calyrex" },
    { pokedexNumber: 899, pokemon: "wyrdeer" },
    { pokedexNumber: 900, pokemon: "kleavor" },
    { pokedexNumber: 901, pokemon: "ursaluna" },
    { pokedexNumber: 902, pokemon: "basculegion" },
    { pokedexNumber: 903, pokemon: "sneasler" },
    { pokedexNumber: 904, pokemon: "overqwil" },
    { pokedexNumber: 905, pokemon: "enamorus" },
];

// adds an event listener to all generation cards
function getUserChoice() {
  for (let i = 0; i < genCards.length; i++) {
    let gen = genCards[i];
    let genId = gen.id;

    gen.addEventListener("click", function () {
      getGen(genId);
    });
  };
};

//depending on which card is clicked, the function passes that array to the startGame function
function getGen(id) {
    switch(id) {
        case "gen1":
            userChoice = gen1;
            loadGameBoard(userChoice);
            break;
        case "gen2":
            userChoice = gen2;
            loadGameBoard(userChoice);
            break;
        case "gen3":
            userChoice = gen3;
            loadGameBoard(userChoice);
            break;
        case "gen4":
            userChoice = gen4;
            loadGameBoard(userChoice);
            break;
        case "gen5":
            userChoice = gen5;
            loadGameBoard(userChoice);
            break;
        case "gen6":
            userChoice = gen6;
            loadGameBoard(userChoice);
            break;
        case "gen7":
            userChoice = gen7;
            loadGameBoard(userChoice);
            break;
        case "gen8":
            userChoice = gen8;
            loadGameBoard(userChoice);
            break;
    }
};

//loads the gameboard page passing in the users choice of array of words to pick from
function loadGameBoard(userChoice) {
  localStorage.setItem("userChoice", JSON.stringify(userChoice));
  location.replace("./gameboard.html");
};

getUserChoice();