const genCards = document.querySelectorAll(".card");
const gen1Card = document.querySelector(".gen1");
const gen2Card = document.querySelector(".gen2");
const gen3Card = document.querySelector(".gen3");
const gen4Card = document.querySelector(".gen4");

let chooseGen;
let userChoice;

const gen1 = [
    { pokedexNumber: 1, pokemon: "bulbasaur" },
    { pokedexNumber: 2, pokemon: "ivysaur" },
    { pokedexNumber: 3, pokemon: "venusaur" },
    { pokedexNumber: 4, pokemon: "charmander" },
    { pokedexNumber: 5, pokemon: "charmeleon" },
    { pokedexNumber: 6, pokemon: "charizard" },
    { pokedexNumber: 7, pokemon: "squirtle" },
    { pokedexNumber: 8, pokemon: "wartortle" },
    { pokedexNumber: 9, pokemon: "blastoise" },
    { pokedexNumber: 10, pokemon: "caterpie" },
    { pokedexNumber: 11, pokemon: "metapod" },
    { pokedexNumber: 12, pokemon: "butterfree" },
    { pokedexNumber: 13, pokemon: "weedle" },
    { pokedexNumber: 14, pokemon: "kakuna" },
    { pokedexNumber: 15, pokemon: "beedrill" },
    { pokedexNumber: 16, pokemon: "pidgey" },
    { pokedexNumber: 17, pokemon: "pidgeotto" },
    { pokedexNumber: 18, pokemon: "pidgeot" },
    { pokedexNumber: 19, pokemon: "rattata" },
    { pokedexNumber: 20, pokemon: "raticate" },
    { pokedexNumber: 21, pokemon: "spearow" },
    { pokedexNumber: 22, pokemon: "fearow" },
    { pokedexNumber: 23, pokemon: "ekans" },
    { pokedexNumber: 24, pokemon: "arbok" },
    { pokedexNumber: 25, pokemon: "pikachu" },
    { pokedexNumber: 26, pokemon: "raichu" },
    { pokedexNumber: 27, pokemon: "sandshrew" },
    { pokedexNumber: 28, pokemon: "sandslash" },
    { pokedexNumber: 29, pokemon: "nidoranf" },
    { pokedexNumber: 30, pokemon: "nidorina" },
    { pokedexNumber: 31, pokemon: "nidoqueen" },
    { pokedexNumber: 32, pokemon: "nidoranm" },
    { pokedexNumber: 33, pokemon: "nidorino" },
    { pokedexNumber: 34, pokemon: "nidoking" },
    { pokedexNumber: 35, pokemon: "clefairy" },
    { pokedexNumber: 36, pokemon: "clefable" },
    { pokedexNumber: 37, pokemon: "vulpix" },
    { pokedexNumber: 38, pokemon: "ninetales" },
    { pokedexNumber: 39, pokemon: "jigglypuff" },
    { pokedexNumber: 40, pokemon: "wigglytuff" },
    { pokedexNumber: 41, pokemon: "zubat" },
    { pokedexNumber: 42, pokemon: "golbat" },
    { pokedexNumber: 43, pokemon: "oddish" },
    { pokedexNumber: 44, pokemon: "gloom" },
    { pokedexNumber: 45, pokemon: "vileplume" },
    { pokedexNumber: 46, pokemon: "paras" },
    { pokedexNumber: 47, pokemon: "parasect" },
    { pokedexNumber: 48, pokemon: "venonat" },
    { pokedexNumber: 49, pokemon: "venomoth" },
    { pokedexNumber: 50, pokemon: "diglett" },
    { pokedexNumber: 51, pokemon: "dugtrio" },
    { pokedexNumber: 52, pokemon: "meowth" },
    { pokedexNumber: 53, pokemon: "persian" },
    { pokedexNumber: 54, pokemon: "psyduck" },
    { pokedexNumber: 55, pokemon: "golduck" },
    { pokedexNumber: 56, pokemon: "mankey" },
    { pokedexNumber: 57, pokemon: "primeape" },
    { pokedexNumber: 58, pokemon: "growlithe" },
    { pokedexNumber: 59, pokemon: "arcanine" },
    { pokedexNumber: 60, pokemon: "poliwag" },
    { pokedexNumber: 61, pokemon: "poliwhirl" },
    { pokedexNumber: 62, pokemon: "poliwrath" },
    { pokedexNumber: 63, pokemon: "abra" },
    { pokedexNumber: 64, pokemon: "kadabra" },
    { pokedexNumber: 65, pokemon: "alakazam" },
    { pokedexNumber: 66, pokemon: "machop" },
    { pokedexNumber: 67, pokemon: "machoke" },
    { pokedexNumber: 68, pokemon: "machamp" },
    { pokedexNumber: 69, pokemon: "bellsprout" },
    { pokedexNumber: 70, pokemon: "weepinbell" },
    { pokedexNumber: 71, pokemon: "victreebel" },
    { pokedexNumber: 72, pokemon: "tentacool" },
    { pokedexNumber: 73, pokemon: "tentacruel" },
    { pokedexNumber: 74, pokemon: "geodude" },
    { pokedexNumber: 75, pokemon: "graveler" },
    { pokedexNumber: 76, pokemon: "golem" },
    { pokedexNumber: 77, pokemon: "ponyta" },
    { pokedexNumber: 78, pokemon: "rapidash" },
    { pokedexNumber: 79, pokemon: "slowpoke" },
    { pokedexNumber: 80, pokemon: "slowbro" },
    { pokedexNumber: 81, pokemon: "magnemite" },
    { pokedexNumber: 82, pokemon: "magneton" },
    { pokedexNumber: 83, pokemon: "farfetchd" },
    { pokedexNumber: 84, pokemon: "doduo" },
    { pokedexNumber: 85, pokemon: "dodrio" },
    { pokedexNumber: 86, pokemon: "seel" },
    { pokedexNumber: 87, pokemon: "dewgong" },
    { pokedexNumber: 88, pokemon: "grimer" },
    { pokedexNumber: 89, pokemon: "muk" },
    { pokedexNumber: 90, pokemon: "shellder" },
    { pokedexNumber: 91, pokemon: "cloyster" },
    { pokedexNumber: 92, pokemon: "gastly" },
    { pokedexNumber: 93, pokemon: "haunter" },
    { pokedexNumber: 94, pokemon: "gengar" },
    { pokedexNumber: 95, pokemon: "onix" },
    { pokedexNumber: 96, pokemon: "drowzee" },
    { pokedexNumber: 97, pokemon: "hypno" },
    { pokedexNumber: 98, pokemon: "krabby" },
    { pokedexNumber: 99, pokemon: "kingler" },
    { pokedexNumber: 100, pokemon: "voltorb" },
    { pokedexNumber: 101, pokemon: "electrode" },
    { pokedexNumber: 102, pokemon: "exeggcute" },
    { pokedexNumber: 103, pokemon: "exegutor" },
    { pokedexNumber: 104, pokemon: "cubone" },
    { pokedexNumber: 105, pokemon: "marowak" },
    { pokedexNumber: 106, pokemon: "hitmonlee" },
    { pokedexNumber: 107, pokemon: "hitmonchan" },
    { pokedexNumber: 108, pokemon: "lickitung" },
    { pokedexNumber: 109, pokemon: "koffing" },
    { pokedexNumber: 110, pokemon: "weezing" },
    { pokedexNumber: 111, pokemon: "rhyhorn" },
    { pokedexNumber: 112, pokemon: "rhydon" },
    { pokedexNumber: 113, pokemon: "chansey" },
    { pokedexNumber: 114, pokemon: "tangela" },
    { pokedexNumber: 115, pokemon: "kangaskhan" },
    { pokedexNumber: 116, pokemon: "horsea" },
    { pokedexNumber: 117, pokemon: "seadra" },
    { pokedexNumber: 118, pokemon: "goldeen" },
    { pokedexNumber: 119, pokemon: "seaking" },
    { pokedexNumber: 120, pokemon: "staryu" },
    { pokedexNumber: 121, pokemon: "starmie" },
    { pokedexNumber: 122, pokemon: "mrmime" },
    { pokedexNumber: 123, pokemon: "scyther" },
    { pokedexNumber: 124, pokemon: "jynx" },
    { pokedexNumber: 125, pokemon: "electabuzz" },
    { pokedexNumber: 126, pokemon: "magmar" },
    { pokedexNumber: 127, pokemon: "pinsir" },
    { pokedexNumber: 128, pokemon: "tauros" },
    { pokedexNumber: 129, pokemon: "magikarp" },
    { pokedexNumber: 130, pokemon: "gyarados" },
    { pokedexNumber: 131, pokemon: "lapras" },
    { pokedexNumber: 132, pokemon: "ditto" },
    { pokedexNumber: 133, pokemon: "eevee" },
    { pokedexNumber: 134, pokemon: "vaporeon" },
    { pokedexNumber: 135, pokemon: "jolteon" },
    { pokedexNumber: 136, pokemon: "flareon" },
    { pokedexNumber: 137, pokemon: "porygon" },
    { pokedexNumber: 138, pokemon: "omanyte" },
    { pokedexNumber: 139, pokemon: "omastar" },
    { pokedexNumber: 140, pokemon: "kabuto" },
    { pokedexNumber: 141, pokemon: "kabutops" },
    { pokedexNumber: 142, pokemon: "aerodactyl" },
    { pokedexNumber: 143, pokemon: "snorlax" },
    { pokedexNumber: 144, pokemon: "articuno" },
    { pokedexNumber: 145, pokemon: "zapdos" },
    { pokedexNumber: 146, pokemon: "moltres" },
    { pokedexNumber: 147, pokemon: "dratini" },
    { pokedexNumber: 148, pokemon: "dragonair" },
    { pokedexNumber: 149, pokemon: "dragonite" },
    { pokedexNumber: 150, pokemon: "mewtwo" },
    { pokedexNumber: 151, pokemon: "mew" }
];

const gen2 = [
    { pokedexNumber: 152, pokemon: "chikorita" },
    { pokedexNumber: 153, pokemon: "bayleef" },
    { pokedexNumber: 154, pokemon: "meganium" },
    { pokedexNumber: 155, pokemon: "cyndaquil" },
    { pokedexNumber: 156, pokemon: "quilava" },
    { pokedexNumber: 157, pokemon: "typhlosion" },
    { pokedexNumber: 158, pokemon: "totodile" },
    { pokedexNumber: 159, pokemon: "croconaw" },
    { pokedexNumber: 160, pokemon: "feraligatr" },
    { pokedexNumber: 161, pokemon: "sentret" },
    { pokedexNumber: 162, pokemon: "furret" },
    { pokedexNumber: 163, pokemon: "hoothoot" },
    { pokedexNumber: 164, pokemon: "noctowl" },
    { pokedexNumber: 165, pokemon: "ledyba" },
    { pokedexNumber: 166, pokemon: "ledian" },
    { pokedexNumber: 167, pokemon: "spinarak" },
    { pokedexNumber: 168, pokemon: "ariados" },
    { pokedexNumber: 169, pokemon: "crobat" },
    { pokedexNumber: 170, pokemon: "chinchou" },
    { pokedexNumber: 171, pokemon: "lanturn" },
    { pokedexNumber: 172, pokemon: "pichu" },
    { pokedexNumber: 173, pokemon: "cleffa" },
    { pokedexNumber: 174, pokemon: "igglybuff" },
    { pokedexNumber: 175, pokemon: "togepi" },
    { pokedexNumber: 176, pokemon: "togetic" },
    { pokedexNumber: 177, pokemon: "natu" },
    { pokedexNumber: 178, pokemon: "xatu" },
    { pokedexNumber: 179, pokemon: "mareep" },
    { pokedexNumber: 180, pokemon: "flaaffy" },
    { pokedexNumber: 181, pokemon: "ampharos" },
    { pokedexNumber: 182, pokemon: "bellossom" },
    { pokedexNumber: 183, pokemon: "marill" },
    { pokedexNumber: 184, pokemon: "azumarill" },
    { pokedexNumber: 185, pokemon: "sudowoodo" },
    { pokedexNumber: 186, pokemon: "politoed" },
    { pokedexNumber: 187, pokemon: "hoppip" },
    { pokedexNumber: 188, pokemon: "skiploom" },
    { pokedexNumber: 189, pokemon: "jumpluff" },
    { pokedexNumber: 190, pokemon: "aipom" },
    { pokedexNumber: 191, pokemon: "sunkern" },
    { pokedexNumber: 192, pokemon: "sunflora" },
    { pokedexNumber: 193, pokemon: "yanma" },
    { pokedexNumber: 194, pokemon: "wooper" },
    { pokedexNumber: 195, pokemon: "quagsire" },
    { pokedexNumber: 196, pokemon: "espeon" },
    { pokedexNumber: 197, pokemon: "umbreon" },
    { pokedexNumber: 198, pokemon: "murkrow" },
    { pokedexNumber: 199, pokemon: "slowking" },
    { pokedexNumber: 200, pokemon: "misdreavus" },
    { pokedexNumber: 201, pokemon: "unown" },
    { pokedexNumber: 202, pokemon: "wobbuffet" },
    { pokedexNumber: 203, pokemon: "girafarig" },
    { pokedexNumber: 204, pokemon: "pineco" },
    { pokedexNumber: 205, pokemon: "forretress" },
    { pokedexNumber: 206, pokemon: "dunsparce" },
    { pokedexNumber: 207, pokemon: "gligar" },
    { pokedexNumber: 208, pokemon: "steelix" },
    { pokedexNumber: 209, pokemon: "snubbull" },
    { pokedexNumber: 210, pokemon: "granbull" },
    { pokedexNumber: 211, pokemon: "qwilfish" },
    { pokedexNumber: 212, pokemon: "scizor" },
    { pokedexNumber: 213, pokemon: "shuckle" },
    { pokedexNumber: 214, pokemon: "heracross" },
    { pokedexNumber: 215, pokemon: "sneasel" },
    { pokedexNumber: 216, pokemon: "teddiursa" },
    { pokedexNumber: 217, pokemon: "ursaring" },
    { pokedexNumber: 218, pokemon: "slugma" },
    { pokedexNumber: 219, pokemon: "magcargo" },
    { pokedexNumber: 220, pokemon: "swinub" },
    { pokedexNumber: 221, pokemon: "piloswine" },
    { pokedexNumber: 222, pokemon: "corsola" },
    { pokedexNumber: 223, pokemon: "remoraid" },
    { pokedexNumber: 224, pokemon: "octillery" },
    { pokedexNumber: 225, pokemon: "delibird" },
    { pokedexNumber: 226, pokemon: "mantine" },
    { pokedexNumber: 227, pokemon: "skarmory" },
    { pokedexNumber: 228, pokemon: "houndour" },
    { pokedexNumber: 229, pokemon: "houndoom" },
    { pokedexNumber: 230, pokemon: "kingdra" },
    { pokedexNumber: 231, pokemon: "phanpy" },
    { pokedexNumber: 232, pokemon: "donphan" },
    { pokedexNumber: 233, pokemon: "porygon2" },
    { pokedexNumber: 234, pokemon: "stantler" },
    { pokedexNumber: 235, pokemon: "smeargle" },
    { pokedexNumber: 236, pokemon: "tyrogue" },
    { pokedexNumber: 237, pokemon: "hitmontop" },
    { pokedexNumber: 238, pokemon: "smoochum" },
    { pokedexNumber: 239, pokemon: "elekid" },
    { pokedexNumber: 240, pokemon: "magby" },
    { pokedexNumber: 241, pokemon: "miltank" },
    { pokedexNumber: 242, pokemon: "blissey" },
    { pokedexNumber: 243, pokemon: "raikou" },
    { pokedexNumber: 244, pokemon: "entei" },
    { pokedexNumber: 245, pokemon: "suicune" },
    { pokedexNumber: 246, pokemon: "larvitar" },
    { pokedexNumber: 247, pokemon: "pupitar" },
    { pokedexNumber: 248, pokemon: "tyranitar" },
    { pokedexNumber: 249, pokemon: "lugia" },
    { pokedexNumber: 250, pokemon: "hooh" },
    { pokedexNumber: 251, pokemon: "celebi" }
];

const gen3 = [
    { pokedexNumber: 252, pokemon: "treecko" },
    { pokedexNumber: 253, pokemon: "groveyle" },
    { pokedexNumber: 254, pokemon: "sceptile" },
    { pokedexNumber: 255, pokemon: "torchic" },
    { pokedexNumber: 256, pokemon: "combusken" },
    { pokedexNumber: 257, pokemon: "blaziken" },
    { pokedexNumber: 258, pokemon: "mudkip" },
    { pokedexNumber: 259, pokemon: "marshtomp" },
    { pokedexNumber: 260, pokemon: "swampert" },
    { pokedexNumber: 261, pokemon: "poochyena" },
    { pokedexNumber: 262, pokemon: "mightyena" },
    { pokedexNumber: 263, pokemon: "zigzagoon" },
    { pokedexNumber: 264, pokemon: "linoone" },
    { pokedexNumber: 265, pokemon: "wurmple" },
    { pokedexNumber: 266, pokemon: "silcoon" },
    { pokedexNumber: 267, pokemon: "beautifly" },
    { pokedexNumber: 268, pokemon: "cascoon" },
    { pokedexNumber: 269, pokemon: "dustox" },
    { pokedexNumber: 270, pokemon: "lotad" },
    { pokedexNumber: 271, pokemon: "lombre" },
    { pokedexNumber: 272, pokemon: "ludicolo" },
    { pokedexNumber: 273, pokemon: "seedot" },
    { pokedexNumber: 274, pokemon: "nuzleaf" },
    { pokedexNumber: 275, pokemon: "shiftry" },
    { pokedexNumber: 276, pokemon: "taillow" },
    { pokedexNumber: 277, pokemon: "swellow" },
    { pokedexNumber: 278, pokemon: "wingull" },
    { pokedexNumber: 279, pokemon: "pelipper" },
    { pokedexNumber: 280, pokemon: "ralts" },
    { pokedexNumber: 281, pokemon: "kirlia" },
    { pokedexNumber: 282, pokemon: "gardevoir" },
    { pokedexNumber: 283, pokemon: "surskit" },
    { pokedexNumber: 284, pokemon: "masqrain" },
    { pokedexNumber: 285, pokemon: "shroomish" },
    { pokedexNumber: 286, pokemon: "breloom" },
    { pokedexNumber: 287, pokemon: "slakoth" },
    { pokedexNumber: 288, pokemon: "vigoroth" },
    { pokedexNumber: 289, pokemon: "slaking" },
    { pokedexNumber: 290, pokemon: "nincada" },
    { pokedexNumber: 291, pokemon: "ninjask" },
    { pokedexNumber: 292, pokemon: "shedinja" },
    { pokedexNumber: 293, pokemon: "whismur" },
    { pokedexNumber: 294, pokemon: "loudred" },
    { pokedexNumber: 295, pokemon: "exploud" },
    { pokedexNumber: 296, pokemon: "makuhita" },
    { pokedexNumber: 297, pokemon: "hariyama" },
    { pokedexNumber: 298, pokemon: "azurill" },
    { pokedexNumber: 299, pokemon: "nosepass" },
    { pokedexNumber: 300, pokemon: "skitty" },
    { pokedexNumber: 301, pokemon: "delcatty" },
    { pokedexNumber: 302, pokemon: "sableye" },
    { pokedexNumber: 303, pokemon: "mawile" },
    { pokedexNumber: 304, pokemon: "aron" },
    { pokedexNumber: 305, pokemon: "lairon" },
    { pokedexNumber: 306, pokemon: "aggron" },
    { pokedexNumber: 307, pokemon: "meditite" },
    { pokedexNumber: 308, pokemon: "medicham" },
    { pokedexNumber: 309, pokemon: "electrike" },
    { pokedexNumber: 310, pokemon: "manectric" },
    { pokedexNumber: 311, pokemon: "plusle" },
    { pokedexNumber: 312, pokemon: "minun" },
    { pokedexNumber: 313, pokemon: "volbeat" },
    { pokedexNumber: 314, pokemon: "illumise" },
    { pokedexNumber: 315, pokemon: "roselia" },
    { pokedexNumber: 316, pokemon: "gulpin" },
    { pokedexNumber: 317, pokemon: "swalot" },
    { pokedexNumber: 318, pokemon: "carvanha" },
    { pokedexNumber: 319, pokemon: "sharpedo" },
    { pokedexNumber: 320, pokemon: "wailmer" },
    { pokedexNumber: 321, pokemon: "wailord" },
    { pokedexNumber: 322, pokemon: "numel" },
    { pokedexNumber: 323, pokemon: "camerupt" },
    { pokedexNumber: 324, pokemon: "torkoal" },
    { pokedexNumber: 325, pokemon: "spoink" },
    { pokedexNumber: 326, pokemon: "grumpig" },
    { pokedexNumber: 327, pokemon: "spinda" },
    { pokedexNumber: 328, pokemon: "trapinch" },
    { pokedexNumber: 329, pokemon: "vibrava" },
    { pokedexNumber: 330, pokemon: "flygon" },
    { pokedexNumber: 331, pokemon: "cacnea" },
    { pokedexNumber: 332, pokemon: "cacturne" },
    { pokedexNumber: 333, pokemon: "swablu" },
    { pokedexNumber: 334, pokemon: "altaria" },
    { pokedexNumber: 335, pokemon: "zangoose" },
    { pokedexNumber: 336, pokemon: "seviper" },
    { pokedexNumber: 337, pokemon: "lunatone" },
    { pokedexNumber: 338, pokemon: "solrock" },
    { pokedexNumber: 339, pokemon: "barboach" },
    { pokedexNumber: 340, pokemon: "whiscash" },
    { pokedexNumber: 341, pokemon: "corphish" },
    { pokedexNumber: 342, pokemon: "crawdaunt" },
    { pokedexNumber: 343, pokemon: "baltoy" },
    { pokedexNumber: 344, pokemon: "claydol" },
    { pokedexNumber: 345, pokemon: "lileep" },
    { pokedexNumber: 346, pokemon: "cradily" },
    { pokedexNumber: 347, pokemon: "anorith" },
    { pokedexNumber: 348, pokemon: "armaldo" },
    { pokedexNumber: 349, pokemon: "feebas" },
    { pokedexNumber: 350, pokemon: "milotic" },
    { pokedexNumber: 351, pokemon: "castform" },
    { pokedexNumber: 352, pokemon: "kecleon" },
    { pokedexNumber: 353, pokemon: "shuppet" },
    { pokedexNumber: 354, pokemon: "banette" },
    { pokedexNumber: 355, pokemon: "duskull" },
    { pokedexNumber: 356, pokemon: "dusclops" },
    { pokedexNumber: 357, pokemon: "tropius" },
    { pokedexNumber: 358, pokemon: "chimecho" },
    { pokedexNumber: 359, pokemon: "absol" },
    { pokedexNumber: 360, pokemon: "wynaut" },
    { pokedexNumber: 361, pokemon: "snorunt" },
    { pokedexNumber: 362, pokemon: "glalie" },
    { pokedexNumber: 363, pokemon: "spheal" },
    { pokedexNumber: 364, pokemon: "sealeo" },
    { pokedexNumber: 365, pokemon: "walrein" },
    { pokedexNumber: 366, pokemon: "clamperl" },
    { pokedexNumber: 367, pokemon: "huntail" },
    { pokedexNumber: 368, pokemon: "gorebyss" },
    { pokedexNumber: 369, pokemon: "relicanth" },
    { pokedexNumber: 370, pokemon: "luvdisc" },
    { pokedexNumber: 371, pokemon: "bagon" },
    { pokedexNumber: 372, pokemon: "shelgon" },
    { pokedexNumber: 373, pokemon: "salamence" },
    { pokedexNumber: 374, pokemon: "beldum" },
    { pokedexNumber: 375, pokemon: "metang" },
    { pokedexNumber: 376, pokemon: "metagross" },
    { pokedexNumber: 377, pokemon: "regirock" },
    { pokedexNumber: 378, pokemon: "regice" },
    { pokedexNumber: 379, pokemon: "registeel" },
    { pokedexNumber: 380, pokemon: "latias" },
    { pokedexNumber: 381, pokemon: "latios" },
    { pokedexNumber: 382, pokemon: "kyogre" },
    { pokedexNumber: 383, pokemon: "groudon" },
    { pokedexNumber: 384, pokemon: "rayquaza" },
    { pokedexNumber: 385, pokemon: "jirachi" },
    { pokedexNumber: 386, pokemon: "deoxys" }
];

const gen4 = [
    { pokedexNumber: 387, pokemon: "turtwig" },
    { pokedexNumber: 388, pokemon: "grotle" },
    { pokedexNumber: 389, pokemon: "torterra" },
    { pokedexNumber: 390, pokemon: "chimchar" },
    { pokedexNumber: 391, pokemon: "monferno" },
    { pokedexNumber: 392, pokemon: "infernape" },
    { pokedexNumber: 393, pokemon: "piplup" },
    { pokedexNumber: 394, pokemon: "prinplup" },
    { pokedexNumber: 395, pokemon: "empoleon" },
    { pokedexNumber: 396, pokemon: "starly" },
    { pokedexNumber: 397, pokemon: "staravia" },
    { pokedexNumber: 398, pokemon: "staraptor" },
    { pokedexNumber: 399, pokemon: "bidoof" },
    { pokedexNumber: 400, pokemon: "bibarel" },
    { pokedexNumber: 401, pokemon: "kricketot" },
    { pokedexNumber: 402, pokemon: "kricketune" },
    { pokedexNumber: 403, pokemon: "shinx" },
    { pokedexNumber: 404, pokemon: "luxio" },
    { pokedexNumber: 405, pokemon: "luxray" },
    { pokedexNumber: 406, pokemon: "budew" },
    { pokedexNumber: 407, pokemon: "roserade" },
    { pokedexNumber: 408, pokemon: "cranidos" },
    { pokedexNumber: 409, pokemon: "rampardos" },
    { pokedexNumber: 410, pokemon: "shieldon" },
    { pokedexNumber: 411, pokemon: "bastiodon" },
    { pokedexNumber: 412, pokemon: "burmy" },
    { pokedexNumber: 413, pokemon: "wormadam" },
    { pokedexNumber: 414, pokemon: "mothim" },
    { pokedexNumber: 415, pokemon: "combee" },
    { pokedexNumber: 416, pokemon: "vespiquen" },
    { pokedexNumber: 417, pokemon: "pachirisu" },
    { pokedexNumber: 418, pokemon: "buizel" },
    { pokedexNumber: 419, pokemon: "floatzel" },
    { pokedexNumber: 420, pokemon: "cherubi" },
    { pokedexNumber: 421, pokemon: "cherrim" },
    { pokedexNumber: 422, pokemon: "shellos" },
    { pokedexNumber: 423, pokemon: "gastrodon" },
    { pokedexNumber: 424, pokemon: "ambipom" },
    { pokedexNumber: 425, pokemon: "drifloon" },
    { pokedexNumber: 426, pokemon: "drifblim" },
    { pokedexNumber: 427, pokemon: "buneary" },
    { pokedexNumber: 428, pokemon: "lopunny" },
    { pokedexNumber: 429, pokemon: "mismagius" },
    { pokedexNumber: 430, pokemon: "honchkrow" },
    { pokedexNumber: 431, pokemon: "glameow" },
    { pokedexNumber: 432, pokemon: "purugly" },
    { pokedexNumber: 433, pokemon: "chingling" },
    { pokedexNumber: 434, pokemon: "stunky" },
    { pokedexNumber: 435, pokemon: "skuntank" },
    { pokedexNumber: 436, pokemon: "bronzor" },
    { pokedexNumber: 437, pokemon: "bronzong" },
    { pokedexNumber: 438, pokemon: "bonsly" },
    { pokedexNumber: 439, pokemon: "mimejr" },
    { pokedexNumber: 440, pokemon: "happiny" },
    { pokedexNumber: 441, pokemon: "chatot" },
    { pokedexNumber: 442, pokemon: "spiritomb" },
    { pokedexNumber: 443, pokemon: "gible" },
    { pokedexNumber: 444, pokemon: "gabite" },
    { pokedexNumber: 445, pokemon: "garchomp" },
    { pokedexNumber: 446, pokemon: "munchlax" },
    { pokedexNumber: 447, pokemon: "riolu" },
    { pokedexNumber: 448, pokemon: "lucario" },
    { pokedexNumber: 449, pokemon: "hippopotas" },
    { pokedexNumber: 450, pokemon: "hippowdon" },
    { pokedexNumber: 451, pokemon: "skorupi" },
    { pokedexNumber: 452, pokemon: "drapion" },
    { pokedexNumber: 453, pokemon: "croagunk" },
    { pokedexNumber: 454, pokemon: "toxicroak" },
    { pokedexNumber: 455, pokemon: "carnivine" },
    { pokedexNumber: 456, pokemon: "finneon" },
    { pokedexNumber: 457, pokemon: "lumineon" },
    { pokedexNumber: 458, pokemon: "mantyke" },
    { pokedexNumber: 459, pokemon: "snover" },
    { pokedexNumber: 460, pokemon: "abomasnow" },
    { pokedexNumber: 461, pokemon: "weavile" },
    { pokedexNumber: 462, pokemon: "magnezone" },
    { pokedexNumber: 463, pokemon: "lickilicky" },
    { pokedexNumber: 464, pokemon: "rhyperior" },
    { pokedexNumber: 465, pokemon: "tangrowth" },
    { pokedexNumber: 466, pokemon: "electivire" },
    { pokedexNumber: 467, pokemon: "magmortar" },
    { pokedexNumber: 468, pokemon: "togekiss" },
    { pokedexNumber: 469, pokemon: "yanmega" },
    { pokedexNumber: 470, pokemon: "leafeon" },
    { pokedexNumber: 471, pokemon: "glaceon" },
    { pokedexNumber: 472, pokemon: "gliscor" },
    { pokedexNumber: 473, pokemon: "mamoswine" },
    { pokedexNumber: 474, pokemon: "porygonz" },
    { pokedexNumber: 475, pokemon: "gallade" },
    { pokedexNumber: 476, pokemon: "probopass" },
    { pokedexNumber: 477, pokemon: "dusknoir" },
    { pokedexNumber: 478, pokemon: "froslass" },
    { pokedexNumber: 479, pokemon: "rotom" },
    { pokedexNumber: 480, pokemon: "uxie" },
    { pokedexNumber: 481, pokemon: "mesprit" },
    { pokedexNumber: 482, pokemon: "azelf" },
    { pokedexNumber: 483, pokemon: "dialga" },
    { pokedexNumber: 484, pokemon: "palkia" },
    { pokedexNumber: 485, pokemon: "heatran" },
    { pokedexNumber: 486, pokemon: "regigigas" },
    { pokedexNumber: 487, pokemon: "giratina" },
    { pokedexNumber: 488, pokemon: "cresselia" },
    { pokedexNumber: 489, pokemon: "phione" },
    { pokedexNumber: 490, pokemon: "manaphy" },
    { pokedexNumber: 491, pokemon: "darkrai" },
    { pokedexNumber: 492, pokemon: "shaymin" },
    { pokedexNumber: 493, pokemon: "arceus" },
];

// adds an event listener to all generation cards
function getUserChoice() {
  for (let i = 0; i < genCards.length; i++) {
    let gen = genCards[i];
    let genId = gen.id;

    gen.addEventListener("click", function () {
      getGen(genId);
    });
  };
};

//depending on which card is clicked, the function passes that array to the startGame function
function getGen(id) {
    switch(id) {
        case "gen1":
            userChoice = gen1;
            loadGameBoard(userChoice, id);
            break;
        case "gen2":
            userChoice = gen2;
            loadGameBoard(userChoice, id);
            break;
        case "gen3":
            userChoice = gen3;
            loadGameBoard(userChoice, id);
            break;
        case "gen4":
            userChoice = gen4;
            loadGameBoard(userChoice, id);
            break;
    }
};

//loads the gameboard page passing in the users choice of array of words to pick from
function loadGameBoard(userChoice, id) {
  localStorage.setItem("userChoice", JSON.stringify(userChoice));
  localStorage.setItem("id", id);
  location.replace("./gameboard.html");
};

getUserChoice();